### ISSUE TITLE
Titre installation et source sans texte

### ISSUE THREAD

**Issue by Odonata971** [quentinformatique/readmeCreator#2]
Titre d'installation et de sources présents alors que je n'ai pas renseigné le champ

![image](https://github.com/quentinformatique/readmeCreator/assets/130738441/e0645aae-14ea-41b7-a306-ad4033c55a00)

![image](https://github.com/quentinformatique/readmeCreator/assets/130738441/fb88ed69-516f-4ba0-9473-cfc2d6007bb4)

**Comment by quentinformatique** [comment]
fixed
